// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.evarist.rootest;

import java.util.List;
import java.util.Random;
import org.evarist.rootest.Activity;
import org.springframework.stereotype.Component;

privileged aspect ActivityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ActivityDataOnDemand: @Component;
    
    private Random ActivityDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Activity> ActivityDataOnDemand.data;
    
    public Activity ActivityDataOnDemand.getNewTransientActivity(int index) {
        org.evarist.rootest.Activity obj = new org.evarist.rootest.Activity();
        setDescription(obj, index);
        setEmail(obj, index);
        setType(obj, index);
        return obj;
    }
    
    private void ActivityDataOnDemand.setDescription(Activity obj, int index) {
        java.lang.String description = "description_" + index;
        obj.setDescription(description);
    }
    
    private void ActivityDataOnDemand.setEmail(Activity obj, int index) {
        java.lang.String email = "email_" + index;
        obj.setEmail(email);
    }
    
    private void ActivityDataOnDemand.setType(Activity obj, int index) {
        java.lang.String type = "type_" + index;
        obj.setType(type);
    }
    
    public Activity ActivityDataOnDemand.getSpecificActivity(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Activity obj = data.get(index);
        return Activity.findActivity(obj.getId());
    }
    
    public Activity ActivityDataOnDemand.getRandomActivity() {
        init();
        Activity obj = data.get(rnd.nextInt(data.size()));
        return Activity.findActivity(obj.getId());
    }
    
    public boolean ActivityDataOnDemand.modifyActivity(Activity obj) {
        return false;
    }
    
    public void ActivityDataOnDemand.init() {
        data = org.evarist.rootest.Activity.findActivityEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Activity' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.evarist.rootest.Activity>();
        for (int i = 0; i < 10; i++) {
            org.evarist.rootest.Activity obj = getNewTransientActivity(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
