// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.evarist.rootest;

import org.evarist.rootest.InterestDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect InterestIntegrationTest_Roo_IntegrationTest {
    
    declare @type: InterestIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: InterestIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: InterestIntegrationTest: @Transactional;
    
    @Autowired
    private InterestDataOnDemand InterestIntegrationTest.dod;
    
    @Test
    public void InterestIntegrationTest.testCountInterests() {
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to initialize correctly", dod.getRandomInterest());
        long count = org.evarist.rootest.Interest.countInterests();
        org.junit.Assert.assertTrue("Counter for 'Interest' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void InterestIntegrationTest.testFindInterest() {
        org.evarist.rootest.Interest obj = dod.getRandomInterest();
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to provide an identifier", id);
        obj = org.evarist.rootest.Interest.findInterest(id);
        org.junit.Assert.assertNotNull("Find method for 'Interest' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Interest' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void InterestIntegrationTest.testFindAllInterests() {
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to initialize correctly", dod.getRandomInterest());
        long count = org.evarist.rootest.Interest.countInterests();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Interest', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.evarist.rootest.Interest> result = org.evarist.rootest.Interest.findAllInterests();
        org.junit.Assert.assertNotNull("Find all method for 'Interest' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Interest' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void InterestIntegrationTest.testFindInterestEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to initialize correctly", dod.getRandomInterest());
        long count = org.evarist.rootest.Interest.countInterests();
        if (count > 20) count = 20;
        java.util.List<org.evarist.rootest.Interest> result = org.evarist.rootest.Interest.findInterestEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Interest' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Interest' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void InterestIntegrationTest.testFlush() {
        org.evarist.rootest.Interest obj = dod.getRandomInterest();
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to provide an identifier", id);
        obj = org.evarist.rootest.Interest.findInterest(id);
        org.junit.Assert.assertNotNull("Find method for 'Interest' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyInterest(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Interest' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InterestIntegrationTest.testMerge() {
        org.evarist.rootest.Interest obj = dod.getRandomInterest();
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to provide an identifier", id);
        obj = org.evarist.rootest.Interest.findInterest(id);
        boolean modified =  dod.modifyInterest(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.evarist.rootest.Interest merged = (org.evarist.rootest.Interest) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Interest' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InterestIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to initialize correctly", dod.getRandomInterest());
        org.evarist.rootest.Interest obj = dod.getNewTransientInterest(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Interest' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Interest' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void InterestIntegrationTest.testRemove() {
        org.evarist.rootest.Interest obj = dod.getRandomInterest();
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Interest' failed to provide an identifier", id);
        obj = org.evarist.rootest.Interest.findInterest(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Interest' with identifier '" + id + "'", org.evarist.rootest.Interest.findInterest(id));
    }
    
}
