// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.evarist.rootest;

import org.evarist.rootest.MyUserDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MyUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MyUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MyUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MyUserIntegrationTest: @Transactional;
    
    @Autowired
    private MyUserDataOnDemand MyUserIntegrationTest.dod;
    
    @Test
    public void MyUserIntegrationTest.testCountMyUsers() {
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to initialize correctly", dod.getRandomMyUser());
        long count = org.evarist.rootest.MyUser.countMyUsers();
        org.junit.Assert.assertTrue("Counter for 'MyUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MyUserIntegrationTest.testFindMyUser() {
        org.evarist.rootest.MyUser obj = dod.getRandomMyUser();
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to provide an identifier", id);
        obj = org.evarist.rootest.MyUser.findMyUser(id);
        org.junit.Assert.assertNotNull("Find method for 'MyUser' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'MyUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MyUserIntegrationTest.testFindAllMyUsers() {
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to initialize correctly", dod.getRandomMyUser());
        long count = org.evarist.rootest.MyUser.countMyUsers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'MyUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.evarist.rootest.MyUser> result = org.evarist.rootest.MyUser.findAllMyUsers();
        org.junit.Assert.assertNotNull("Find all method for 'MyUser' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'MyUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MyUserIntegrationTest.testFindMyUserEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to initialize correctly", dod.getRandomMyUser());
        long count = org.evarist.rootest.MyUser.countMyUsers();
        if (count > 20) count = 20;
        java.util.List<org.evarist.rootest.MyUser> result = org.evarist.rootest.MyUser.findMyUserEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'MyUser' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'MyUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MyUserIntegrationTest.testFlush() {
        org.evarist.rootest.MyUser obj = dod.getRandomMyUser();
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to provide an identifier", id);
        obj = org.evarist.rootest.MyUser.findMyUser(id);
        org.junit.Assert.assertNotNull("Find method for 'MyUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMyUser(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'MyUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MyUserIntegrationTest.testMerge() {
        org.evarist.rootest.MyUser obj = dod.getRandomMyUser();
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to provide an identifier", id);
        obj = org.evarist.rootest.MyUser.findMyUser(id);
        boolean modified =  dod.modifyMyUser(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.evarist.rootest.MyUser merged = (org.evarist.rootest.MyUser) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'MyUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MyUserIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to initialize correctly", dod.getRandomMyUser());
        org.evarist.rootest.MyUser obj = dod.getNewTransientMyUser(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'MyUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'MyUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MyUserIntegrationTest.testRemove() {
        org.evarist.rootest.MyUser obj = dod.getRandomMyUser();
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MyUser' failed to provide an identifier", id);
        obj = org.evarist.rootest.MyUser.findMyUser(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'MyUser' with identifier '" + id + "'", org.evarist.rootest.MyUser.findMyUser(id));
    }
    
}
