// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.evarist.rootest;

import java.lang.String;

privileged aspect Interest_Roo_JavaBean {
    
    public String Interest.getType() {
        return this.type;
    }
    
    public void Interest.setType(String type) {
        this.type = type;
    }
    
}
